import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# GLPI API CONFIG
GLPI_API_URL = os.getenv("GLPI_API_URL")
GLPI_API_APP_TOKEN = os.getenv("GLPI_API_APP_TOKEN")
GLPI_API_USER_TOKEN = os.getenv("GLPI_API_USER_TOKEN")


# OPENAI API CONFIG
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MAX_SIMILAR_TICKETS_FOR_RELATED = 6
MAX_SIMILAR_TICKETS_FOR_ANSWER = 3
SIMILARITY_THRESHOLD_FOR_RESPONSE = 0.94511
SIMILARITY_THRESHOLD_FOR_SEARCHBYID = SIMILARITY_THRESHOLD_FOR_RESPONSE - 0.03
EMBEDDING_MODEL = "text-embedding-ada-002"
OPENAI_EMBEDDING_ENDPOINT = "https://api.openai.com/v1/embeddings"
TIME_TO_WAIT_BETWEEN_EMBEDDING_REQUESTS = 22  # The FREE rate limit is 3 per minute.
CHAT_RESPONSE_TEMPERATURE = 0.2
CHAT_RESPONSE_MAX_TOKENS = 450
CHAT_RESPONSE_MODEL = "gpt-3.5-turbo-16k"
